<!DOCTYPE html>
<html lang="zh-tw">
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>Aoetw</title>
    <style>
      body {        padding-top: 0px;        font-family: "微軟正黑體";        background-color: #f5f5f5;        font-size: 18px;        }    .tit{        margin: 20px auto 20px auto;        background: url(img/title3.jpg);         width:100%;         height: 284px;         text-align: center;        color: aliceblue;        padding-top: 50px;    }    .tt{        font-size: 45px;        font-weight: bold;    }    .tt2{        font-size: 30px;        font-weight: bold;        margin-right: 530px;    }.wimg{  width:300px ;  height: 250px;}.we{  font-size: 20px;}.unititle,.unititle2{  color: #fff;}.tor img{  margin-right: 5px;  width: 22px;  padding-bottom: 2px;}
    </style>
  </head>
  
  <body>
    <?php include( "head.php"); ?>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row" style=" margin-top: 50px;">
        <h1>臺港知名玩家</h1>
        <div class="spw"><em><img src="img/tola.jpg" width="50px;" alt="" style="margin-right:20px;">持續更新頁面：任何意見，歡迎到<a href="talk.php">討論區</a>參與討論</em>
        </div>
        <div class="hrn1"></div>
        <div class="n1">
          <p>本頁面主要介紹活躍於臺灣、香港Steam上的知名玩家，接地氣，如果要看世界級的高手請到：<a href="top.php">世界知名玩家</a>
          </p>
          <p>目前已經收錄<span style="color: red">127</span>名玩家啦！ 最後修改日期：2018/11/12</p>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;border-top: 1px solid #c7c7c7;">
        <div class="col-md-12">
          <table class="table">
            <tr>
              <td>
                <h4><strong>cheap</strong></h4>
              </td>
            </tr>
            <tr>
              <td>Aoetw創建者，2k2單挑型玩家，vo短暫站上19+。團戰不太行，前期弄人偷豬專家，能快攻就不會龜經濟，市集愛好者，配置一團亂，但能靠臨場反應將劣勢化為優勢。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>kevin19817051</strong></h4>
              </td>
            </tr>
            <tr>
              <td>凱文，vo17玩家，偶而爬上18+，毅力驚人，不怕輸總敢跟比自己強的打，團戰打的好，單挑偏向圍家，打防守反擊。後期非常可怕，不過只用匈奴是他的弱點。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Black Jack</strong></h4>
              </td>
            </tr>
            <tr>
              <td>黑傑克，臺灣新興高手，2k2玩家。控兵、意識都不錯，噁心肉馬晃到你頭昏眼花，就是聲音太猥瑣。團戰坐中經濟穩定發揮，坐邊可取得優勢，弱點是只會用馬扎爾。(目前已經消失匿跡)</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Sky and Peace</strong><img src="https://pokemon.gameinfo.io/images/pokemon/216.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>天空熊，台灣新興高手，年僅18歲，2k3玩家，操作觀念俱好，單挑團戰都打的不錯，內家打的比外家好，可能是台灣下一顆耀眼之星。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Lucky Cat tw</strong></h4>
              </td>
            </tr>
            <tr>
              <td>招財貓，阿拉伯黑森林玩家，2k實力，打cheap專家，只要和cheap同隊必搓、同邊必雷，敵隊便viper上身，擅長游牧黑森林。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>arlokwood</strong></h4>
              </td>
            </tr>
            <tr>
              <td>澳門王，馬爆，2k2燥底玩家，實力堅強，經濟流高手，團戰比單挑猛很多，經濟調配的很好，大後期無能可敵，黑森林比阿拉伯更強。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>卡姆</strong>&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Creative-Tail-Animal-dog.svg/2000px-Creative-Tail-Animal-dog.svg.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>卡姆，香港玩家，賽馬愛好者，菜雞聯盟主席。一邊打賽馬一邊打世紀卻變成15+實力。認真打的時候，實力可達到Steam 20+ 實力，蘿莉看過卡姆打局後，斷言卡姆有22+的實力。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>鳳凰蘇</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>台灣15+做正經事女玩家，幾乎天天都打世紀，可以打贏不少台灣男玩家，曾打敗卡姆。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>雨沛</strong>&nbsp;<img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>雨沛，臺灣活躍女玩家，喜歡條頓與特殊兵種條頓武士。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>丹布倫</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>台灣知名女插畫家，會開插畫直播，<a href="https://www.facebook.com/DanbulunII/">粉絲專頁</a>，網路上擁有廣大粉絲，也是世紀愛好者，常常愛用塔攻，值得一提的是她用繪圖版打世紀。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>阿維子</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>女玩家，也是插畫家，只是是業餘的，夜貓ai開場者，不過愛好打40分條約。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Ada</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>旅澳女玩家，一個年輕辣媽，愛打無海牧地，實力還不錯，會開直播，<a href="https://www.twitch.tv/ada_lee">直播網址</a>。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>lala</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>黑50分女玩家，爆經濟不錯，聲音甜美身材火辣，擁有為數不少的粉絲。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>這我一定吉</strong><img src="img/law-512.pngn" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>cheap的大乾爹，打AI常常到帝王的時候可以派出很多的兵種，是一個AI高手，唯獨對真人作戰比較會手忙腳亂。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>DDL (五月天)</strong></h4>
              </td>
            </tr>
            <tr>
              <td>世紀帝國唯一玩家兼戰地記者、播報員，擁有2172+的帳號，實力暫時不明，有時廢如柴，有時勇如虎。擅長一邊打局一邊播報戰況(如：這間軍營裡面出來三隻民兵，往我家走了)，疑似為cheap的粉絲，其優點是被踢房仍能再加打死不退，蘿莉斷言認真打有vo19～2k實力，相當恐怖。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>陳轄</strong></h4>
              </td>
            </tr>
            <tr>
              <td>陳轄看眠大直播一年半，深夜帶打AI高手-實力應該有17～18+左右。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>太陽神的翼神龍</strong></h4>
              </td>
            </tr>
            <tr>
              <td>chirs，約18～19+實力，心態容易炸裂。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>老毛星</strong></h4>
              </td>
            </tr>
            <tr>
              <td>觀念型玩家，擁有超群23+觀念，但操作由13+進步到16+，可以打嬴不少Steam18+高手。有時候直播打有海的地型，都可以馬上成為19+的高手。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>彰化骰子肉圓</strong></h4>
              </td>
            </tr>
            <tr>
              <td>愛約戰 經常出現黑林阿拉伯，實力約1800上下，不時出現在cheap直播間唱歌。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>BattleAngel</strong></h4>
              </td>
            </tr>
            <tr>
              <td>小xx，以前黑森林玩家，常出現美女場，經濟型玩家，20+經濟高手。近來有出現阿拉伯，19+的實力</td>
            </tr>
            <tr>
              <td>
                <h4><strong>怨尤絲</strong></h4>
              </td>
            </tr>
            <tr>
              <td>魷魚絲海戰高手，現實中也是個小籠包甜點製作高手。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>王阿姨</strong></h4>
              </td>
            </tr>
            <tr>
              <td>就算最後一兵一卒也要打下去，是一個永不放棄的人。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>泡泡俠</strong>&nbsp;<img src="https://p2.bahamut.com.tw/HOME/creationCover/91/0003928791_B.PNG" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>第三人稱射擊遊戲高手，不管CSGO、PUBG都玩的很好，但世紀帝國稍微弱了一點。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>馬丁</strong></h4>
              </td>
            </tr>
            <tr>
              <td>第三人稱射擊遊戲高手，PUBG都玩的很好，曾單場16殺，但世紀帝國萬年14+，甚至一度13+。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>0殺吃雞王 Jerry</strong></h4>
              </td>
            </tr>
            <tr>
              <td>少見的博士玩家，專長0殺安全帽吃雞更是一絕。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>甲甲妖精王</strong></h4>
              </td>
            </tr>
            <tr>
              <td>知名實況主Reo，各種地圖都玩的不錯，重點和cheap一樣，也是個帥哥。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>姆咪</strong></h4>
              </td>
            </tr>
            <tr>
              <td>虐菜型玩家，虐菜虐到2100+，也算是奇杷。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>一路發</strong></h4>
              </td>
            </tr>
            <tr>
              <td>18～19+馬雅玩家，前期打的不錯，帝王後沒後勁，太偏軍事。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>咪嚕咕</strong>&nbsp;<img src="https://cdn1.iconfinder.com/data/icons/food-drinks-2/512/milk-512.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>經典國王被投石機砸死。(<a href="https://www.youtube.com/watch?v=xuur0nGnfB0">影片</a>)</td>
            </tr>
            <tr>
              <td>
                <h4><strong>黑豬</strong>&nbsp;<img src="https://png.icons8.com/metro/1600/pig.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>把妹高達25+的高手</td>
            </tr>
            <tr>
              <td>
                <h4><strong>01 112233</strong></h4>
              </td>
            </tr>
            <tr>
              <td>數字，世紀帝國老玩家，打法相當聰明，實力非常強，Voo約18+左右。Ptt世紀板主，舉辦過大型比賽，不吝於提攜後進。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>iAMsotO</strong></h4>
              </td>
            </tr>
            <tr>
              <td>steam 2k實力，團戰表現突出，輸出穩定，總體上中間打的比邊國好，前期如果沒有優勢，打法會趨於保守。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Dodolu</strong></h4>
              </td>
            </tr>
            <tr>
              <td>香港玩家，港臺少見的死鬥高手，團戰單挑都不錯，發揮穩定，後期非常的強。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Mimi</strong></h4>
              </td>
            </tr>
            <tr>
              <td>骰子型玩家，發揮不是很穩定，偶而有驚人曠世之舉，邊家容易被打爆。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>wakaka889466</strong></h4>
              </td>
            </tr>
            <tr>
              <td>挖咖咖，澳門高手，cs玩家，2018年初進步得很快，團戰打的不錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Nick (HK ARENA)</strong></h4>
              </td>
            </tr>
            <tr>
              <td>Nick，知名host，長駐14+，但圍城打的還可以，中規中矩，會爆經濟會打前置，但前置明顯打的不怎樣，無法攻守兼具。偏好義大利傭兵，只會打圍城。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Soweak</strong></h4>
              </td>
            </tr>
            <tr>
              <td>圍城玩家，還算穩定，打法多變，有時老鷹、有時馬爆，偶而僧侶前置神來一筆，爆經濟時也可以Carry全場，只是不多見。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Pablo871</strong></h4>
              </td>
            </tr>
            <tr>
              <td>秋天，圍城黑森林玩家，西班牙控，火槍愛好者，很少打前置快攻，攻守發揮的中規中矩讓人安心。其實阿拉伯也是打的還OK。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Clever_Dragon</strong></h4>
              </td>
            </tr>
            <tr>
              <td>聰明龍，香港玩家，阿拉伯圍城都打的還可以，喜好單挑，團戰實力不穩定。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>diun27</strong></h4>
              </td>
            </tr>
            <tr>
              <td>丹尼27，澳門人，圍城王，能前置就不會龜，圍城打的非常好，前置打死一家後還可以發展自己。其封建轉帝王打法更是讓人嚇破膽。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Yoshi_Lum</strong><img src="img/tork.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>耀西，香港圍城玩家，烏龜王，經濟發展型玩家，但非常可靠，龜出來不會讓隊友失望。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Jack</strong><img src="img/tor.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>香港圍城玩家，偏好龜家，還算可以龜出東西，弱化版耀西，發揮沒有曜西、hunki這種烏龜王穩定，弱化版烏龜王。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>tung</strong><img src="img/tork.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>頂級香港圍城烏龜王，進化版耀西，穩定爆經濟高手，28分前絕對出關殺敵。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Shearfai</strong></h4>
              </td>
            </tr>
            <tr>
              <td>香港圍城玩家，快攻型，較少打經濟發展，升級穩健、打法新穎，可靠的隊友。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>hungki824</strong><img src="img/tork.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>香港2k黑森林、圍城玩家，烏龜王，能龜就不會打快，事實上是每場都龜，但能龜出火力給予對手支援。有一陣子因為老婆不給玩，淡出世紀圈。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>matthew_kolokolo</strong></h4>
              </td>
            </tr>
            <tr>
              <td>馬修，香港玩家，打法全面，圍城阿拉伯都會打，比較愛打前期。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Marco</strong></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣圍城土耳其王，只會用土耳其，但把土耳其打的出神入化，團戰還算穩定。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>封弟</strong></h4>
              </td>
            </tr>
            <tr>
              <td>鳳凰蘇的小跟班。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>yoyo</strong></h4>
              </td>
            </tr>
            <tr>
              <td>實力約2k1，團戰穩定發揮，不常出錯，打法有自信。單挑相對比團戰肉了一點。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>yushtang</strong></h4>
              </td>
            </tr>
            <tr>
              <td>布丁，臺灣知名老玩家，成名的早，單挑團戰都打的不錯，匈奴的搶城戰術更是所有玩家的惡夢，在ptt有多篇<a href="https://pttweb.tw/aoe/m-1497345471-a-f71.html">精湛教學</a>。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Mashirou</strong></h4>
              </td>
            </tr>
            <tr>
              <td>2k2玩家，阿拉伯圍城都打的很好，團戰非常穩健，跟他同邊非常的舒服。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>stu18004077</strong></h4>
              </td>
            </tr>
            <tr>
              <td>侑晉，2K玩家，進步頗快，單挑團戰都還可以。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Rory</strong></h4>
              </td>
            </tr>
            <tr>
              <td>蘿莉，Voobly 19+玩家，臺灣團戰除了雲以外的第一高手高手高高手，團戰意識突出，單挑也非常的強，熟悉新舊文明各種兵種與打法。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Onjbb</strong></h4>
              </td>
            </tr>
            <tr>
              <td>香港玩家，Voobly單挑曾經上過2k，單挑非常的猛，前置高手，其4村民前置槍矛的打法讓人聞風喪膽，團戰就沒有單挑這麼有威力。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Ckfr2014</strong></h4>
              </td>
            </tr>
            <tr>
              <td>Ray，香港玩家，Voobly團戰達18+之譜，團戰單挑都不錯，但團戰更令人驚豔，曾打贏過越南第一高手bact。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>apple_inoob</strong></h4>
              </td>
            </tr>
            <tr>
              <td>Apple，臺灣老玩家，實力不錯，團戰單挑都打的很好，且不限於阿拉伯地形。喜歡大象、象弓、越南。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Blackmore_Night</strong></h4>
              </td>
            </tr>
            <tr>
              <td>香港人，圍城阿拉伯都打的不錯，打法多變，不過有時候會龜家。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Tomggyy</strong></h4>
              </td>
            </tr>
            <tr>
              <td>2k1玩家，團戰單挑都打的不錯，團戰很穩，不容易出錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>公主殿下</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿拉伯玩家，實力超群，控馬控的很強。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>do not kick my ass</strong></h4>
              </td>
            </tr>
            <tr>
              <td>18+玩家，城快愛好者，上城堡後不好打，但在城堡前打爆他非常容易。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>金正恩</strong></h4>
              </td>
            </tr>
            <tr>
              <td>18+玩家，本來也是城快愛好者，但偶而會打封快或前置。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>倉B</strong></h4>
              </td>
            </tr>
            <tr>
              <td>18+玩家，但無法應付更高等級的團戰水平。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>qaws68</strong></h4>
              </td>
            </tr>
            <tr>
              <td>伊森博士，對於任何世紀帝國硬體軟體上的問題都非常熟悉，熱心助人，遊戲也打的不錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Cockateil </strong></h4>
              </td>
            </tr>
            <tr>
              <td>約2k實力，中規中矩。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>湯可男</strong></h4>
              </td>
            </tr>
            <tr>
              <td>湯哥，臺灣世紀圈的老前輩，與早期臺灣高手都熟識，有很多精采故事，實力也堅強，現在偶而會打打steam的團戰。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>阿崙</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿崙，湯哥的好朋友，2k3實力，單挑打法穩健，團戰攻守兼備，28分即可輸出一隊騎兵掃場。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Aluba</strong></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣元老級神獸玩家，與曾政承同時代，曾經代表臺灣參加過世界大賽，並得到冠軍，現在仍活躍於世紀圈。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>superdurian</strong></h4>
              </td>
            </tr>
            <tr>
              <td>超級榴槤，2k玩家，肉馬控的不錯，經濟也調配的很好。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>blue_way</strong></h4>
              </td>
            </tr>
            <tr>
              <td>穩健型玩家，經濟控的不錯，較缺乏攻擊慾望，故黑森林、圍城打的比阿拉伯好。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Daniel_____</strong></h4>
              </td>
            </tr>
            <tr>
              <td>丹尼，旅美香港頂尖玩家，voobly2k3實力，2018年5月忽然爆強，幾乎是港臺最強高手，單挑團戰都是超群水準，能與世界一級高手viper、yo等人一同團戰實力。老婆是一個叫做虎哥的女子。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Suika</strong></h4>
              </td>
            </tr>
            <tr>
              <td>2k2玩家，單挑團戰都打的不錯，經濟流玩家。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>herb</strong></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣知名玩家，實力頂尖，大肉馬愛好者，淫蕩手速抓村民之快，讓人聞風喪膽。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Levi_</strong></h4>
              </td>
            </tr>
            <tr>
              <td>LB，Voobly 19+玩家，臺灣戰隊RoAmEr_的創辦者，臺灣第二高手，單挑團戰、意識控兵都達到一流水準。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Dai</strong></h4>
              </td>
            </tr>
            <tr>
              <td>帥哥，城快時代便非常出名，台灣少數上過vo2k的玩家。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>小夜夜</strong></h4>
              </td>
            </tr>
            <tr>
              <td>知名lol選手，天才型玩家，接觸世紀帝國短短幾個月便可與高手一較高下。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Yi</strong></h4>
              </td>
            </tr>
            <tr>
              <td>洨鮮肉，Voobly 19+玩家，攻守兼具。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Randy Chen</strong></h4>
              </td>
            </tr>
            <tr>
              <td>藍迪，臺灣老玩家，單挑打的不錯。vo 16～17+水準。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>=qp=</strong></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣知名host，GTA5發行後，現在比較少打，愛好各種地圖與打法。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>egg</strong></h4>
              </td>
            </tr>
            <tr>
              <td>老玩家，阿拉伯遊牧打的不錯，現沉迷於電子鴉片，文明帝國。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>seed</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿拉伯打的不錯，2k玩家，現在較少出沒。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>mimiking</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿拉伯2k玩家，坐中還可以，邊國打的不太行，戰術較為保守。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>AK47</strong></h4>
              </td>
            </tr>
            <tr>
              <td>團戰小天使，曾經極速上過Voobly19+的玩家，但退化的也快，目前就steam2k～2k1遊走，團戰打的不錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Ming Feng Chen(Feng) </strong></h4>
              </td>
            </tr>
            <tr>
              <td>敏芳，常打阿拉伯，實力約18+左右，但其實是黑森林玩家，在黑森林爆經濟可與一線高手較量，偶像是台灣歐吉桑。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Candy</strong><img src="img/love.png" width="45" alt=""><img src="img/194394.svg" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣女玩家，18~19+，顏值很高，身材很好，阿拉伯打的也非常好，擅長使用匈奴。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Nakiki</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣女玩家，美女，身材極度火辣，專打黑森林，義大利打的很好，其他文明就較為普通，發揮的不是很穩定，邊家常常自爆，但內家可穩定發展，圍牆女王。值得一提的是有為數眾多的親衛隊。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>張筑</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣女玩家，喜歡打阿拉伯，興趣是用自製OP地圖虐不知情玩家。謠傳有一個很會打世紀的哥哥，有時候會偷代打</td>
            </tr>
            <tr>
              <td>
                <h4><strong>沐沐</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>愛睡覺的貓，臺灣女玩家，超級美女，愛打ai。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>特級砂糖</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣女玩家，身材好的美女，愛打ai。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>雪雪</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>雪雪，臺灣女玩家，身材好的正妹，愛打ai。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Munzo</strong><img src="img/love.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>馬祖，香港女玩家，Voobly1750+以上水準，阿拉伯打的極好，偏好團戰勝於單挑。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Lastmantilldie</strong></h4>
              </td>
            </tr>
            <tr>
              <td>日本玩家，實力2k上下，圍城阿拉伯都會打，烏龜型，但常常龜不出什麼東西，實力發揮不穩定，且很會lag。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>terrant</strong></h4>
              </td>
            </tr>
            <tr>
              <td>日本阿拉伯玩家，實力2k上下，打法穩健，坐中時有獨特打法，五民兵跳城堡，非常特殊。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>工人強出頭</strong></h4>
              </td>
            </tr>
            <tr>
              <td>steam19+玩家，打世紀帝國歷史悠久，從yahoo奇摩家族年代就浪跡天崖，實力穩紮穩打，缺點是只會打阿拉伯，其他地圖偏弱。</td>
            </tr>
             <tr>
              <td>
                <h4><strong>kimo ota</strong></h4>
              </td>
            </tr>
            <tr>
              <td>日本黑森林玩家，steam經歷很久，但實力捉摸不定，上過2k也下過16+，愛開pk。</td>
            </tr>

            <tr>
              <td>
                <h4><strong>Tai-wei</strong></h4>
              </td>
            </tr>
            <tr>
              <td>steam上過2k的玩家，但團戰不太穩定。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Lugano</strong></h4>
              </td>
            </tr>
            <tr>
              <td>Nakiki親衛隊長，黑森林實力雄厚，擅長農經濟打大規模兵戰。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>＠＠～</strong></h4>
              </td>
            </tr>
            <tr>
              <td>眼鏡哥，steam19+阿拉伯玩家，但打法過於保守，實力發揮不穩定。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Kuo</strong></h4>
              </td>
            </tr>
            <tr>
              <td>郭先生，steam19+玩家，阿拉伯會前置會塔攻，目前看來是黑森林玩家。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>bomb445</strong></h4>
              </td>
            </tr>
            <tr>
              <td>炸彈王，老玩家，圍城打的比阿拉伯好，但沉迷於實況，只看臺不打了。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Deep lin</strong></h4>
              </td>
            </tr>
            <tr>
              <td>steam 2k玩家，打法較偏保守，不容易出錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>台中梨鳴</strong>&nbsp;<img src="https://cdn2.iconfinder.com/data/icons/thesquid-ink-40-free-flat-icon-pack/64/rubber-duck-512.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>長期1750～18遊走，遊牧比阿拉伯會打，阿拉伯和黑森林暫時來看只有16+實力。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>胡四</strong></h4>
              </td>
            </tr>
            <tr>
              <td>辦過大型比賽，擅長論述，steam18+。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>@@!</strong></h4>
              </td>
            </tr>
            <tr>
              <td>@@!打工仔，俊億哥，時常與眼鏡哥搞混。黑森林混分王，只是打工的，打順風球很不錯，只要逆風就會開始打假球甚至裝死，打假球就是假裝還在玩，但行為匪夷所思，感覺就是在等投降，例如用矛兵丟城堡，裝死就是直接去看足球。名言是：我認真起來連我自己都怕。實際上都是靠同盟給予大量資源才會逆轉。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Iamhowgim</strong></h4>
              </td>
            </tr>
            <tr>
              <td>皓鈞，台灣極少數上過voo20+玩家，控馬非常強，意識也很好。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>農夫</strong></h4>
              </td>
            </tr>
            <tr>
              <td>元老級高手玩家，從綠阿城快時代便非常有名，現在穩定VO19+。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Kyo</strong></h4>
              </td>
            </tr>
            <tr>
              <td>少林金剛腿，人稱腿哥，臺灣資深國寶級玩家，擅長海戰，經常在阿拉伯出船防守，還曾經在比賽黑森林地圖中，在對方家旁邊蓋碼頭出火炮戰船﻿。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>okduck</strong><img src="img/tor.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>ok鴨，香港15+玩家，但圍城打的不錯，最弱版烏龜王，匈奴垃圾兵愛好者。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>rayray</strong><img src="img/tor.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>香港16+圍城玩家，西班牙愛好者，烏龜流，不過是愛好西班牙垃圾兵配火炮塔陣，與ok鴨長期敵對。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>PAI</strong></h4>
              </td>
            </tr>
            <tr>
              <td>團戰發揮穩定，中規中矩。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>littlebone</strong></h4>
              </td>
            </tr>
            <tr>
              <td>小骨頭，萬年16+玩家，遊牧打的還不錯。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>AOC歐吉桑</strong></h4>
              </td>
            </tr>
            <tr>
              <td>黑森林50+(年紀)老玩家，實力約16+，興趣廣泛，會彈琴、會種菜，也喜歡電玩。年輕時曾在公司成立AOC戰略研究社。2017年受念大學的兒子影響，重新回鍋玩世紀。喜歡和大家一起玩團戰，有品不亂棄，是大家玩AOE的好朋友。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>老師不要</strong></h4>
              </td>
            </tr>
            <tr>
              <td>老師不要，台灣玩家，老遊戲愛好者。喜歡打黑森50，但是常常揪不到人。曾經用垃圾兵擋住cheap3分鐘，最近閃婚了，剩一張嘴。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>小太陽</strong></h4>
              </td>
            </tr>
            <tr>
              <td>18～19+玩家，圍城阿拉伯都會打，後期偶而會有神來之筆。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Unique Nick</strong></h4>
              </td>
            </tr>
            <tr>
              <td>臺灣Nick，黑森林玩家，賽爾特愛好者，實力堅強。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>evil_dragon</strong></h4>
              </td>
            </tr>
            <tr>
              <td>邪龍，18+玩家，名氣很大。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>冰妖精</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿拉伯玩家，實力普普18+，但似乎對很多玩家很瞭解。對於世紀帝國的兵種數據也很熟稔，人稱世紀維基百科。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>老k</strong></h4>
              </td>
            </tr>
            <tr>
              <td>黑森林玩家，賽爾特愛好者，實力堅強，對於ai也非常有研究。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>就是Rock</strong></h4>
              </td>
            </tr>
            <tr>
              <td>ai愛好者，時常開ai給大家同樂。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>熊老闆</strong></h4>
              </td>
            </tr>
            <tr>
              <td>ai愛好者，愛慕糖果。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>way</strong></h4>
              </td>
            </tr>
            <tr>
              <td>香港老玩家，阿拉伯圍城都打的不錯，打法全面。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>Sharktooth Bowman</strong></h4>
              </td>
            </tr>
            <tr>
              <td>鯊魚，老玩家，匈奴愛好者，阿拉伯打的很溜。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>嘉明</strong></h4>
              </td>
            </tr>
            <tr>
              <td>阿拉伯2k玩家，團戰發揮的很好。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>apencilbox</strong></h4>
              </td>
            </tr>
            <tr>
              <td>鉛筆盒，印加和塔攻愛好者，有陣子單挑一定場場塔攻。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>a4892929</strong></h4>
              </td>
            </tr>
            <tr>
              <td>a48，單挑團戰都打的不錯，尤其團戰坐中發揮的很好。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>長安</strong><img src="img/tor.png" width="45" alt=""></h4>
              </td>
            </tr>
            <tr>
              <td>旅日中國玩家，賣隊友高手，實力不錯，但愛偷經濟，導致隊友被打爆。</td>
            </tr>
            <tr>
              <td>
                <h4><strong>池塘海洋兒</strong></h4>
              </td>
            </tr>
            <tr>
              <td>洋洋，阿拉伯與黑森林玩家，分數很低，不到1300+，12出頭，但對遊戲很熱情，常常開場。</td>
            </tr>
          </table>
        </div>
      </div>
      <!-- /container -->
      <?php include( "foot.php"); ?>
  </body>

</html>